#!/bin/bash

# Créer la VM
qm create 100 \
  --name aqua_db \
  --ostype l26 \
  --machine q35 \
  --bios ovmf \
  --cpu host \
  --cores 2 \
  --memory 8192 \
  --balloon 4096 \
  --net0 virtio,bridge=vmbr0,firewall=1 \
  --scsihw virtio-scsi-single \
  --scsi0 local-lvm:100,cache=writeback,discard=on,iothread=1 \
  --ide2 local:iso/debian-13.4.0-amd64-netinst.iso,media=cdrom \
  --boot order=ide2\;scsi0 \
  --agent enabled=1 \
  --efidisk0 local-lvm:4M