# Generated by Django 6.0.2 on 2026-03-01 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aquarium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=25)),
                ('volume_eau', models.IntegerField()),
                ('date_mise_en_service', models.DateField()),
                ('commentaire', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Analyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no2', models.FloatField(max_length=5)),
                ('no3', models.FloatField(max_length=5)),
                ('ph', models.FloatField(max_length=5)),
                ('nh4', models.FloatField(max_length=5)),
                ('kh', models.FloatField(max_length=5)),
                ('gh', models.FloatField(max_length=5)),
                ('sio2', models.FloatField(max_length=5)),
                ('po4', models.FloatField(max_length=5)),
                ('mg', models.FloatField(max_length=5)),
                ('fe', models.FloatField(max_length=5)),
                ('cu', models.FloatField(max_length=5)),
                ('observation', models.CharField(max_length=100)),
                ('aquarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aquariums.aquarium')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeEau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_change_eau', models.DateField()),
                ('quantite_litre', models.IntegerField()),
                ('osmose_pourcentage', models.IntegerField()),
                ('robinet_pourcentage', models.IntegerField()),
                ('aquarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aquariums.aquarium')),
            ],
        ),
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=25)),
                ('quantite', models.IntegerField(help_text='en ml')),
                ('date_traitement', models.DateField()),
                ('aquarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aquariums.aquarium')),
            ],
        ),
    ]
