# Generated by Django 6.0.2 on 2026-03-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquariums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyse',
            name='tds',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
