# Generated by Django 6.0.2 on 2026-03-03 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquariums', '0002_analyse_tds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Espece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_espece', models.CharField(max_length=25)),
                ('type_espece', models.CharField(max_length=25)),
                ('nombre_espece', models.IntegerField()),
                ('paramettre_min_ph', models.FloatField()),
                ('paramettre_max_ph', models.FloatField()),
                ('paramettre_eau', models.CharField(max_length=25)),
                ('aquarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aquariums.aquarium')),
            ],
        ),
        migrations.CreateModel(
            name='Plante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_plante', models.CharField(max_length=25)),
                ('emplacement_aquarium', models.CharField(choices=[('ARRIERE PLAN', 'Arrière Plan'), ('MILIEU PLAN', 'Milieu Plan'), ('PREMIER PLAN', 'Premier Plan'), ('SUR OBJET', 'Sur Objet')], max_length=25)),
                ('paramettre_min_ph', models.FloatField()),
                ('paramettre_max_ph', models.FloatField()),
                ('paramettre_min_co2', models.FloatField()),
                ('paramettre_max_co2', models.FloatField()),
                ('aquarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aquariums.aquarium')),
            ],
        ),
    ]
