# Generated by Django 6.0.3 on 2026-03-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquariums', '0004_equipement'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='carateristique',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipement',
            name='commentaire',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipement',
            name='date_installation',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
