# Generated by Django 6.0.3 on 2026-03-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquariums', '0005_equipement_carateristique_equipement_commentaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='carateristique',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plante',
            name='emplacement_aquarium',
            field=models.CharField(choices=[('ARRIERE PLAN', 'Arrière Plan'), ('MILIEU PLAN', 'Milieu Plan'), ('PREMIER PLAN', 'Premier Plan'), ('SUR OBJET', 'Sur Objet'), ('FLOTANTE', 'Flottante'), ("N'IMPORTE OU", "N'importe où")], max_length=25),
        ),
    ]
